### ISSUE TITLE
new method unfamiliar

### ISSUE THREAD

**Issue by lizzie92869** [learn-co-curriculum/rails-form_for-lab#6]
This is not an issue but a suggestion. Up to this point in the curriculum we never saw a .new in the new action. It looks weird at first (even if understandable) to have (without previous explanation): 
def new
@student = Student.new
end

Also when we are not familiar with the syntax it can look like we are gonna hit a conflit while creating a row with the create action right after on the same instance. 
It would be nice to have a little paragraph in the lesson about this. thanks

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
