### ISSUE TITLE
Breaking update for factory_bot throws errors

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/rails-form_for-lab#9]
spec/factories/school_classes.rb throws an error:

FactoryBot.define do
  factory :school_class do
    title "Computer Science"  # undefined method title
    room_number 5
  end
end

The only way I found to fix this was forcing the program to use factory_bot v. 4.8.2 with factory_bot_rails 4.8.2.

Once those version are in gemfile.lock then students can do their migrations, whereas before rake db:migrate and similar commands with bundle exec would simply throw errors traced to factor_bot gem.

**Comment by aaj3f** [comment]
I am having the same issue.

**Comment by levimllr** [comment]
I am getting an error related to factories:

`An error occurred while loading ./spec/controllers/school_classes_controller_spec.rb.
Failure/Error: title "Computer Science"

NoMethodError:
  undefined method 'title' in 'school_class' factory`

My code produces the right behavior; it may be that the methods used in the spec files are beyond deprecated.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
